connector_image: customer-io-source
tests:
  spec:
    - spec_path: "test_files/spec.json"
  connection:
    - status: "succeed"
    - config_path: "test_files/invalid_config.json"
      status: "failed"
  basic_read:
    - configured_catalog_path: "test_files/full_configured_catalog.json"
      expect_records:
        path: "test_files/expected_records.txt"
        extra_fields: true
        exact_order: true
        extra_records: false
  full_refresh:
    - configured_catalog_path: "test_files/full_configured_catalog.json"
  incremental:
    - configured_catalog_path: "test_files/incremental_configured_catalog.json"
      future_state_path: "test_files/abnormal_state.json"
      cursor_paths:
        campaigns: [ "cutoff" ]
        campaign_actions: [ "cutoff" ]
        newsletters: [ "cutoff" ]
